export type SensorId = "oxygen" | "temperature" | "water";
export type ActuatorId = "oxygenator" | "cooling" | "pump";
export type Readings = Record<SensorId, number>;
export type Rule = { sensor: SensorId; actuator: ActuatorId; threshold: number };
export type SystemDefinition = {
  id: SensorId;
  symbol: string;
  nameZh: string;
  nameEn: string;
  shortZh: string;
  unit: string;
  min: number;
  max: number;
  step: number;
  idealThreshold: number;
  goodRange: [number, number];
  condition: string;
  conditionEn: string;
  actuator: ActuatorId;
  actuatorZh: string;
  actuatorEn: string;
};
export type Mission = {
  number: string;
  titleZh: string;
  titleEn: string;
  objective: string;
  ai: string;
  required: SensorId[];
  setupTime: number;
  start: Readings;
  guided: boolean;
};
export const SYSTEMS: Record<SensorId, SystemDefinition>;
export const ACTUATORS: Array<{ id: ActuatorId; code: string; nameZh: string; nameEn: string }>;
export const MISSIONS: Mission[];
export const DEFAULT_THRESHOLDS: Record<SensorId, number>;
export function isRuleValid(rule: Rule): boolean;
export function validateRules(mission: Mission, rules: Rule[]): { success: boolean; issues: string[] };
export function calculateEnergy(mission: Mission, rules: Rule[]): number;
export function advanceReadings(readings: Readings, mission: Mission, rules: Rule[]): Readings;
export function calculateScore(mission: Mission, rules: Rule[], timeLeft: number, mistakes: number): number;
