export const GAME_CATALOG = [
  {
    slug: "mars-iot-rescue",
    href: "/games/mars-iot-rescue/",
    number: "01",
    title: "Mars IoT Rescue",
    topic: "Internet of Things",
    level: "S3",
    duration: "8–10 min",
    status: "READY",
  },
  {
    slug: "uno-wiring",
    href: "/games/uno-wiring/",
    number: "02",
    title: "點亮第一顆 LED",
    topic: "Arduino · 接線與數位輸出",
    level: "S3",
    duration: "8–10 min",
    status: "READY",
  },
  {
    slug: "three-light-lab",
    href: "/games/three-light-lab/",
    number: "03",
    title: "三色燈實驗室",
    topic: "Arduino · 程式次序與三色燈",
    level: "S3",
    duration: "8–10 min",
    status: "READY",
  },
  {
    slug: "sensor-readings",
    href: "/games/sensor-readings/",
    number: "04",
    title: "讓電腦看見光",
    topic: "Arduino · 感應器與電腦讀數",
    level: "S3",
    duration: "8–10 min",
    status: "READY",
  },
] as const;
