'use client';
import { LIGHTS, PARTS } from './game-data.mjs';
import type { Circuit,Part } from './game-data.mjs';
export type Selection={channel:number;part:Part|'ground'}|null;
const letters='abcdefghij';
function point(h:string){const r=letters.indexOf(h[0]);return {x:309+(Number(h.slice(1))-1)*28,y:151+r*25+(r>=5?22:0)};}
export function Breadboard({wiring,count,channel,selection,hints,powered,choose,pin,place,output=[false,false,false],demo=false}:{wiring:Circuit;count:number;channel:number;selection:Selection;hints:boolean;powered:boolean;output?:boolean[];demo?:boolean;choose:(s:Selection)=>void;pin:(p:number)=>void;place:(h:string)=>void}){
 const selected=selection?.part;
 const light=LIGHTS[channel];
 function path(a:string,b:string,color:string,key:string){if(!a||!b)return null;const p=point(a),q=point(b);return <path key={key+a+b} className="tl-draw" pathLength="1" d={`M${p.x} ${p.y} Q${(p.x+q.x)/2} ${Math.max(100,Math.min(p.y,q.y)-35)} ${q.x} ${q.y}`} stroke={color} strokeWidth="3" fill="none"/>;}
 const nextPart=PARTS.find(([part])=>!wiring.lights[channel].holes[part])?.[0];
 const active=selection || (nextPart?{channel,part:nextPart}:!wiring.ground?{channel,part:'ground' as const}:null);
 const target=active?(active.part==='ground'?'f2':LIGHTS[active.channel].guide[active.part]):null;
 const label=(part:Part|'ground')=>part==='ground'?'共用 GND 幹線':PARTS.find(([k])=>k===part)?.[1];
 const pairs=[['anode','cathode','一顆 LED','長腳 ＋','短腳 −'],['r1','r2','一顆 220 Ω 電阻（共兩腳）','第一腳','同一顆的第二腳'],['back','join','這顆燈的回路線','LED 短腳端','共同接地端']] as const;
 return <>{!demo&&<><div className="tl-step" role="status"><b>{powered?'USB 已連接：先完成亮滅測試':active?`下一步：${selection?'插入':'選取'}${label(active.part)}`:'接線端點齊備，連接 USB 檢查及測試'}</b><p>{!powered&&active&&(selection?`已選${LIGHTS[active.channel].name} · ${label(active.part)}，現在點${hints?` ${target}（發光孔）`:'麵包板目標孔'}。`:`點下方「${label(active.part)}」${active.part==='signal'?`或 Uno D${light.pin}`:active.part==='ground'?'或 Uno GND':''}，再點${hints?` ${target}（發光孔）`:'你選擇的孔位'}。`)}</p></div>
 <div className="tl-parts">{pairs.map(([first,second,title,a,b])=><div className="tl-component" key={first}><b>{title}</b><svg viewBox="0 0 130 45" aria-hidden="true"><path d="M15 35L45 20M85 20L115 35" stroke="#71847c" strokeWidth="3"/>{first==='anode'?<path d="M45 25V15a20 14 0 0 1 40 0v10Z" fill={light.color}/>:first==='r1'?<g><rect x="43" y="10" width="44" height="20" rx="5" fill="#dec096"/><path d="M53 10v20m8-20v20m12-20v20" stroke="#ad3434" strokeWidth="4"/></g>:<path d="M45 20Q65 0 85 20" fill="none" stroke={light.color} strokeWidth="4"/>}</svg>{[[first,a],[second,b]].map(([part,text])=><button key={part} disabled={powered} aria-pressed={selected===part&&selection?.channel===channel} onClick={()=>choose({channel,part:part as Part})}>{label(part as Part)}<small>{text} · {wiring.lights[channel].holes[part as Part]||'未接'}</small></button>)}</div>)}
 <div className="tl-component"><b>Uno 接線</b><button disabled={powered} aria-pressed={selected==='signal'} onClick={()=>pin(light.pin)}>訊號線<small>D{wiring.lights[channel].pin} → {wiring.lights[channel].holes.signal||'未接'}</small></button><button disabled={powered} aria-pressed={selected==='ground'} onClick={()=>choose({channel,part:'ground'})}>共用 GND 幹線<small>Uno GND → {wiring.ground||'未接'} · 三燈共用一條</small></button></div></div>
 <p className="tl-board-help">每顆 LED 有一條回路線；三條回路經麵包板相通孔，共用一條 GND 幹線。點已接端點可重新選取及改接。</p>
 <p>麵包板已橫放：數字由左至右、字母由上至下；同一數字 a–e 相通，f–j 相通，中間凹槽隔開。{hints&&'綠色長框示範 f2–j2 內部相通，並非額外元件。'}</p></>}
 <div className="tl-board-scroll" role="region" aria-label="Uno 與完整麵包板接線圖"><div className="tl-board">
 <svg viewBox="0 0 1060 470" aria-hidden="true">
 <defs><pattern id="tl-dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#ccd8cf"/></pattern></defs><rect width="1060" height="470" rx="12" fill="url(#tl-dots)"/>
 <text x="23" y="45" fill="#275c50" fontSize="21" fontWeight="bold">Arduino Uno R3</text>
 <rect x="23" y="117" width="238" height="230" rx="13" fill="#087f87" stroke="#126771" strokeWidth="3"/>{[[35,132],[246,132],[35,333],[246,333]].map(([x,y])=><circle key={x+y} cx={x} cy={y} r="6" fill="#dee7cd"/>)}
 <rect x="8" y="166" width="50" height="48" fill="#b0c1c2" stroke="#647981" strokeWidth="3"/><rect x="8" y="174" width="12" height="32" fill="#354b50"/><text x="23" y="156" fill="white" fontSize="12">USB</text>
 <text x="78" y="235" fill="white" fontSize="37" fontWeight="bold">UNO</text><rect x="93" y="266" width="111" height="29" rx="3" fill="#163c42"/>{Array.from({length:11},(_,i)=><path key={i} d={`M${97+i*10} 260v6m0 29v6`} stroke="#bccac4" strokeWidth="3"/>)}<text x="98" y="283" fill="#c3d6cd" fontSize="9">ATmega328P</text>
 <circle cx="64" cy="274" r="10" fill="#b9cfc4"/><circle cx="64" cy="305" r="10" fill="#b9cfc4"/>
 <rect x="107" y="137" width="133" height="28" fill="#213e40"/><rect x="132" y="310" width="98" height="24" fill="#213e40"/>
 <text x="288" y="71" fill="#275c50" fontSize="21" fontWeight="bold">麵包板 Breadboard</text><text x="288" y="93" fill="#5a7568" fontSize="12">橫放後，同一數字的 a–e 相通；f–j 相通。中央凹槽分隔兩邊。</text>
 <rect x="279" y="112" width="763" height="306" rx="12" fill="#fffef5" stroke="#c1cbb9" strokeWidth="2"/><rect x="288" y="265" width="743" height="14" rx="4" fill="#d1d8c8"/>
 {Array.from({length:26},(_,i)=><text key={i} x={309+i*28} y="135" textAnchor="middle" fill="#4e6c5b" fontSize="10">{i+1}</text>)}{letters.split('').map((l,i)=><text key={l} x="287" y={155+i*25+(i>=5?22:0)} fill="#4e6c5b" fontSize="11">{l}</text>)}
 {(hints||demo)&&<rect x="328" y="287" width="18" height="113" rx="9" fill="#319b7633" stroke="#278665" strokeWidth="2"/>}
 {wiring.ground&&<path key={wiring.ground} className="tl-draw" pathLength="1" d={`M180 325 Q245 445 ${point(wiring.ground).x} ${point(wiring.ground).y}`} stroke="#244951" strokeWidth="4" fill="none"/>}
 {wiring.lights.slice(0,count).map((v,i)=>{const h=v.holes,c=LIGHTS[i].color;const a=h.anode?point(h.anode):null,b=h.cathode?point(h.cathode):null,r=h.r1?point(h.r1):null,s=h.r2?point(h.r2):null;return <g key={i}>{h.signal&&<path className="tl-draw" key={h.signal+v.pin} pathLength="1" d={`M${128+(v.pin-8)*43} 151 Q260 115 ${point(h.signal).x} ${point(h.signal).y}`} stroke={c} strokeWidth="3" fill="none"/>}{path(h.back,h.join,c,`back${i}`)}{a&&b&&<g><path d={`M${a.x} ${a.y}L${(a.x+b.x)/2} ${(a.y+b.y)/2}L${b.x} ${b.y}`} stroke="#89978e" strokeWidth="3"/><path d={`M${(a.x+b.x)/2-9} ${(a.y+b.y)/2+4}v-8a9 9 0 0 1 18 0v8Z`} fill={output[i]?c:'#88938d'} stroke={c} strokeWidth={output[i]?5:1}/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-18} textAnchor="middle" fill="#244951" fontSize="11">{LIGHTS[i].name} {output[i]?'亮':'滅'}</text></g>}{r&&s&&<g><path d={`M${r.x} ${r.y}L${s.x} ${s.y}`} stroke="#89978e" strokeWidth="3"/><rect x={(r.x+s.x)/2-14} y={(r.y+s.y)/2-6} width="28" height="12" rx="3" fill="#dec096"/>{['#ad3434','#ad3434','#784e32'].map((color,j)=><rect key={j} x={(r.x+s.x)/2-8+j*6} y={(r.y+s.y)/2-6} width="3" height="12" fill={color}/>)}</g>}</g>;})}
 {selection&&['signal','ground'].includes(selection.part)&&<path d={selection.part==='ground'?'M180 325 Q245 420 275 360':`M${128+(wiring.lights[selection.channel].pin-8)*43} 151 Q240 90 280 145`} stroke={selection.part==='ground'?'#244951':LIGHTS[selection.channel].color} strokeWidth="4" strokeDasharray="6 4" fill="none"/>}
 {selection&&['back','r1','r2','join'].includes(selection.part)&&(()=>{const h=wiring.lights[selection.channel].holes;const start=selection.part==='join'?h.back:selection.part==='r2'?h.r1:'';if(!start)return null;const p=point(start);return <path d={`M${p.x} ${p.y}q20 -40 48 -20`} stroke={light.color} strokeWidth="4" strokeDasharray="6 4" fill="none"/>;})()}
 <text x="23" y="400" fill="#526a5b" fontSize="12">D8 紅 · D9 綠 · D10 黃</text><text x="289" y="446" fill="#526a5b" fontSize="12">只在端點接通。線跨過其他孔不代表接通。每顆 LED 各用一顆 220 Ω 電阻。</text>
 </svg>
 {[8,9,10].map((p,i)=><button key={p} className="tl-pin" style={{left:`${(128+i*43)/10.6}%`,top:`${151/4.7}%`}} aria-pressed={selected==='signal'&&wiring.lights[channel].pin===p} disabled={powered} onClick={()=>pin(p)} aria-label={`Uno D${p}`}><i/>D{p}</button>)}<button className="tl-pin" style={{left:`${180/10.6}%`,top:`${325/4.7}%`}} aria-pressed={selected==='ground'} disabled={powered} onClick={()=>choose({channel,part:'ground'})} aria-label="Uno GND"><i/>GND</button>
 {Array.from({length:26},(_,col)=>letters.split('').map(l=>{const hole=`${l}${col+1}`,p=point(hole);const located=wiring.lights.findIndex(v=>Object.values(v.holes).includes(hole));const used=located>=0||wiring.ground===hole;const endpoint=located>=0?Object.entries(wiring.lights[located].holes).find(([,h])=>h===hole)?.[0] as Part:undefined;return <button key={hole} className={`tl-hole ${used?'used':''} ${hints&&target===hole&&!powered?'tl-target':''}`} style={{left:`${p.x/10.6}%`,top:`${p.y/4.7}%`,...(used?{background:located>=0?LIGHTS[located].color:'#244951'}:{})}} disabled={powered} aria-label={`孔 ${hole}`} title={`${hole}${endpoint?' · '+LIGHTS[located].name+' '+label(endpoint):wiring.ground===hole?' · GND 幹線':''}`} onClick={()=>{if(!selection&&used)choose({channel:located>=0?located:channel,part:endpoint||'ground'});else place(hole);}}>{used?(endpoint?({anode:'＋',cathode:'−',r1:'R',r2:'R',signal:'S',back:'↩',join:'↩'}[endpoint]):'G'):''}</button>;}))}
 </div></div><p className="tl-mobile-note">孔位保持大小；窄畫面可左右捲動接線圖。</p></>;
}
