export type Part = 'anode'|'cathode'|'r1'|'r2'|'signal'|'back'|'join';
export type Circuit = {ground:string;lights:{holes:Record<Part,string>;pin:number}[]};
export type Instruction = {type:'write';pin:number;level:string}|{type:'delay';ms:number}|{type:'missing'};
export type Frame={index:number;state:boolean[];elapsed:number;duration:number};
export type Answer={states:number[];seconds:string};
export const LIGHTS: {name:string;pin:number;color:string;guide:Record<Part,string>}[];
export const PARTS: [Part,string][];
export function emptyCircuit():Circuit;
export function net(hole:string):string|null;
export function occupied(w:Circuit,hole:string,channel:number,key:Part|'ground'):boolean;
export function checkCircuit(w:Circuit,count:number):{safe:boolean;ok:boolean;safety:string[];results:{ok:boolean;text:string}[]};
export function write(pin:number,level:string):Instruction;
export function delay(ms:number):Instruction;
export function stage(pin:number,ms:number):Instruction[];
export const PREDICTION:Instruction[];
export const ORIGINAL:Instruction[];
export const BROKEN:Instruction[];
export function trace(program:Instruction[],initial?:boolean[]):Frame[];
export function stableStages(program:Instruction[]):Frame[];
export function predictionCorrect(answers:Answer[],program?:Instruction[]):boolean;
export function timingCorrect(program:Instruction[],seconds:string):boolean;
export function repairCorrect(program:Instruction[]):boolean;
export function instructionText(i:Instruction):string;
export function testOutput(wiring:Circuit,count:number,code:{modePin:string;writePin:string;level:string},previous:boolean[]):boolean[];
export function pairedEnd(part:Part|'ground'):Part|null;
