'use client';
import { useEffect,useRef,useState } from 'react';
import { CurrentFlow } from './CurrentFlow';
import { LightCover } from './LightCover';
import { SensorBoard } from './SensorBoard';
import { PARTS,CONDITIONS,emptyWiring,pair,checkWiring,reading,validateCode,serialState,evidenceCorrect } from './game-data.mjs';
import type { Part,Code,Records } from './game-data.mjs';
const BASE=process.env.NEXT_PUBLIC_BASE_PATH??'';
type Phase='teach'|'mode'|'wire'|'observe'|'explain'|'reconnect'|'done';
type Sample={value:number;condition:string;number:number};
const initialCode:Code={baud:9600,pin:'A0',print:true,delay:500};
const emptyRecords=():Records=>({bright:[],shade:[],dark:[]});
export function SensorLab(){
 const [currentWatched,setCurrentWatched]=useState(false);
 const [phase,setPhase]=useState<Phase>('teach'),[lesson,setLesson]=useState(0),[review,setReview]=useState(false);
 const [mode,setMode]=useState<'practice'|'challenge'>('practice'),[hint,setHint]=useState(false),[hints,setHints]=useState(0);
 const [demoCover,setDemoCover]=useState(0);
 const demoCondition=demoCover<25?'bright':demoCover>75?'dark':'shade';
 const [cover,setCover]=useState(0),[movingCover,setMovingCover]=useState(false);
 function changeCover(value:number){setCover(value);setCondition(value<25?'bright':value>75?'dark':'shade');setSamples([]);}
 const monitorSection=useRef<HTMLElement>(null);
 useEffect(()=>{if(phase==='observe')monitorSection.current?.scrollIntoView({block:'start'});},[phase]);
 const [message,setMessage]=useState('今次不接 LED：讓電腦看見光暗。先用短教學認識輸入，再親手接線。');
 const [wiring,setWiring]=useState(emptyWiring),[selected,setSelected]=useState<Part|null>(null),[resistance,setResistance]=useState(10000),[power,setPower]=useState(false);
 const [code,setCode]=useState<Code>(initialCode),[verified,setVerified]=useState(false),[uploaded,setUploaded]=useState<Code|null>(null);
 const [port,setPort]=useState(''),[monitor,setMonitor]=useState(false),[baud,setBaud]=useState(115200);
 const [condition,setCondition]=useState('bright'),[samples,setSamples]=useState<Sample[]>([]),[records,setRecords]=useState<Records>(emptyRecords),[retest,setRetest]=useState<Records>(emptyRecords);
 const [bright,setBright]=useState(''),[dark,setDark]=useState(''),[trend,setTrend]=useState(''),[unit,setUnit]=useState(''),[factor,setFactor]=useState('');
 const counter=useRef(0);
 const circuit=checkWiring(wiring,resistance),environment=CONDITIONS.find(c=>c.id===condition)!;
 const serialError=serialState({power,uploaded,port,monitor,baud,kind:circuit.kind});
 const next=selected||PARTS.find(([p])=>!wiring[p])?.[0];
 const selectedLabel=PARTS.find(([p])=>p===next)?.[1];
 const target=PARTS.find(([p])=>p===next)?.[2];
 const collecting=phase==='observe'||phase==='reconnect';
 useEffect(()=>{
  if(!collecting||serialError||!uploaded||movingCover)return;
  const timer=setInterval(()=>{const number=counter.current++;const value=reading(90-cover*.85,circuit.kind,resistance,number);if(value!==null)setSamples(rows=>[...rows,{value,condition,number}].slice(-12));},uploaded.delay);
  return()=>clearInterval(timer);
 },[collecting,serialError,uploaded,cover,movingCover,circuit.kind,resistance,condition]);
 const fresh=samples.filter(s=>s.condition===condition).slice(-3);
 const table=phase==='reconnect'?retest:records;
 function clearRun(){setUploaded(null);setSamples([]);if(phase==='reconnect')setRetest(emptyRecords());else setRecords(emptyRecords());}
 function select(part:Part){if(power)return;setSelected(part);setMessage(`已選${PARTS.find(([p])=>p===part)?.[1]}。${hint?`點 ${PARTS.find(([p])=>p===part)?.[2]}（突出孔位）。`:'現在點麵包板目標孔。'}`);}
 function place(h:string){
  if(power)return;if(!selected){setMessage('先選元件的一腳或 Uno 腳位，再點孔位；已接端點可點選改接。');return;}
  if(PARTS.some(([p])=>p!==selected&&wiring[p]===h)){setMessage(`${h} 已有線頭；每孔只插一個線頭，請選同組另一個空孔。`);return;}
  if(wiring[selected]===h){setSelected(null);return;}
  const w={...wiring,[selected]:h},end=pair(selected);setWiring(w);setSelected(end);clearRun();
  const result=checkWiring(w,resistance);
  setMessage(end?`已接 ${h}；現在接同一元件的第二腳。`:result.ready?phase==='reconnect'?'A0 已重新接好。接 USB，重新驗證及上傳，再測光與暗。':'接線完成。檢查電阻數值，然後進入 Serial Monitor。':!result.safe?result.text:`已接 ${h}。${Object.values(w).every(Boolean)?result.text:'按「下一步」繼續接線。'}`);
 }
 function togglePower(){if(!power&&!circuit.safe){setMessage(circuit.text);return;}setPower(!power);setSelected(null);clearRun();setMessage(power?'USB 已拔除。可以改線；改好後重新驗證及上傳。':'USB 已連接。選 Uno 的 COM3，驗證程式，再上傳。');}
 function help(){setMode('practice');setHint(true);setHints(hints+1);setMessage(phase==='explain'?'從自己的表選光、暗各一個讀數。光讀數較大；這些是原始數值，並非 lux。':phase==='observe'?'Serial Monitor 要和 Serial.begin(9600) 相同速率。每種光度等待三個新讀數，再記錄。':'已開啟逐步提示，進度保留。A0 讀取 LDR 和 10 kΩ 電阻中間的共用接點。');}
 function changeCode(nextCode:Code){setCode(nextCode);setVerified(false);setMessage('編輯器已修改。執行中的仍是上次上傳版本；先驗證，再重新上傳。');}
 function upload(){
  if(!power){setMessage('未能上傳：先接 USB。');return;}if(port!=='COM3'){setMessage('未能上傳：這塊 Uno 接在 COM3，請核對連接埠。');return;}
  if(!verified){setMessage('先按「驗證程式」，再上傳。');return;}
  setUploaded({...code});setSamples([]);if(phase==='reconnect')setRetest(emptyRecords());else setRecords(emptyRecords());setMessage('程式已上傳。開啟 Serial Monitor，核對通訊速率，觀察每半秒出現一行讀數。');
 }
 function record(){
  if(movingCover||serialError||!circuit.ready||fresh.length<3){setMessage('先讓正確電路及 Serial Monitor 顯示這種光度的三個新讀數。');return;}
  const values=fresh.map(s=>s.value);if(phase==='reconnect')setRetest({...retest,[condition]:values});else setRecords({...records,[condition]:values});setMessage(`已記錄「${environment.name}」：${values.join('、')}。${phase==='reconnect'?'再測另一種光度。':'切換光度，等三個新讀數，再記錄。'}`);
 }
 function start(mode:'practice'|'challenge'){setMode(mode);setHint(mode==='practice');setPhase('wire');setMessage('由空白麵包板開始。先選 LDR 第一腳，再點孔位；接好第一腳會自動選第二腳。');}
 function finishEvidence(){if(!evidenceCorrect(records,bright,dark,trend,unit,factor)){setMessage('請引用表內的光、暗讀數，比較大小，並檢查單位和讀數波動的原因。');return;}
  setPhase('reconnect');setPower(false);setUploaded(null);setSamples([]);setMonitor(false);setVerified(false);setWiring({...wiring,input:''});setSelected(null);setHint(false);setMessage('獨立檢核：已斷電並移除 A0 線，其餘電路保留。自己接回 A0，再上傳及記錄光、暗各三個讀數。需要時仍可求提示。');}
 function download(){const text=`感應器與電腦讀數 · 單元三\n${mode==='challenge'?'獨立完成':'練習完成'}\n模擬讀數，並非實物測量或 lux。\n${CONDITIONS.map(c=>`${c.name}：${records[c.id].join('、')}`).join('\n')}\n光線充足 ${bright} > 完全遮蓋 ${dark}，本課接法越光讀數越高。\n波動因素：${({shadow:'手部遮光程度',position:'光源位置',noise:'感應器與取樣的微小波動'} as Record<string,string>)[factor]}\nA0 重接後：光 ${retest.bright.join('、')}；暗 ${retest.dark.join('、')}\n`;
  const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='單元三_感應器實驗記錄.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function teaching(){return <section className="sr-card sr-lesson"><div className="sr-section-head"><span>共同教學 · {lesson+1} / 3</span><button onClick={()=>review?setReview(false):setPhase('mode')}>{review?'返回任務':'跳過教學，選擇模式'} →</button></div>{lesson===0?<><h2>上次讓燈亮，今次讓電腦「看見」光。</h2><div className="sr-flow"><span>環境光度 ☀</span><b>→</b><span>LDR 電路</span><b>→</b><span>A0 輸入</span><b>→</b><span>電腦讀數</span></div><p>A0 是輸入（Input），讀取接點電壓；上一單元 D8 用 digitalWrite() 控制 LED 輸出（Output）。</p><div className="sr-demo"><LightCover value={demoCover} onChange={setDemoCover}/><div><h3>試試遮住 LDR</h3>{CONDITIONS.map(c=><button key={c.id} aria-pressed={demoCondition===c.id} onClick={()=>setDemoCover(c.id==='bright'?0:c.id==='shade'?50:100)}>{c.name}</button>)}</div><output>{reading(90-demoCover*.85)}<small>模擬 analogRead(A0) · 原始值</small></output></div><p>Uno R3 預設參考電壓下，約 0–5 V 對應 0–1023。這不是 lux，亦不是 HIGH／LOW 兩個值。</p></>:lesson===1?<><h2>A0 接在兩個元件中間。</h2><p>LDR 與 <strong>一顆 10 kΩ 固定電阻</strong>組成分壓電路；兩種元件均無正負方向。10 kΩ = 10000 Ω，並非上一課的 220 Ω。</p><CurrentFlow onComplete={()=>setCurrentWatched(true)}/><p className="sr-note">綠框是麵包板第 8 列本身相通的孔：a8（LDR）、e8（電阻）及 c8（A0）。不是額外元件。A0 量度這個共同接點。</p></>:<><h2>讀取 → 儲存 → 傳送 → 等待</h2><ol className="sr-explain-code"><li><code>Serial.begin(9600);</code><span>在 setup 啟動序列通訊；監控視窗也選 9600。</span></li><li><code>int sensorValue = analogRead(A0);</code><span>把這次 A0 讀到的整數放入變數 sensorValue。</span></li><li><code>Serial.println(sensorValue);</code><span>把數值傳到電腦，每個數值另起一行。</span></li><li><code>delay(500);</code><span>等待半秒，再重複讀取。本課模擬每 500 ms 取樣。</span></li></ol><p>電腦沒有數據：檢查 USB、上傳和連接埠。出現亂碼：檢查兩邊通訊速率。一直是 0 或 1023：先斷電，再檢查 A0 接點。</p></>}<div className="sr-actions">{lesson>0&&<button onClick={()=>setLesson(lesson-1)}>← 上一步</button>}<button className="sr-primary" disabled={lesson===1&&!currentWatched} onClick={()=>lesson<2?setLesson(lesson+1):review?setReview(false):setPhase('mode')}>{lesson===1&&!currentWatched?'先看一次電流示範':lesson<2?'下一段教學 →':review?'返回任務 →':'開始選擇模式 →'}</button></div></section>;}
 function recordsTable(data:Records){return <div className="sr-table-scroll"><table><caption>觀察記錄 · 模擬原始值（0–1023）</caption><thead><tr><th>光度</th><th>第一次</th><th>第二次</th><th>第三次</th></tr></thead><tbody>{CONDITIONS.filter(c=>phase!=='reconnect'||c.id!=='shade').map(c=><tr key={c.id}><th>{c.name}</th>{[0,1,2].map(i=><td key={i}>{data[c.id]?.[i]??'—'}</td>)}</tr>)}</tbody></table></div>;}
 return <main className="sr-lab"><nav><a href={`${BASE}/`}>← LUI SIR’S ICT GAME LAB</a><span>UNIT 03 · SENSORS & DATA</span></nav><header><div><p className="sr-eyebrow">接線 · 遮光 · 收集證據</p><h1>讓電腦<span>看見光</span></h1><p>感應器與電腦讀數 / LDR Sensor Lab</p></div><div className="sr-progress">{({teach:'先學方法',mode:'選擇模式',wire:'01 接好感應器',observe:'02 收集讀數',explain:'03 用數據解釋',reconnect:'04 獨立重接',done:'實驗完成'})[phase]}{!['teach','mode'].includes(phase)&&<small>{mode==='practice'?'練習模式':'自我挑戰'} · 無倒數</small>}</div></header>
 <section className="sr-feedback"><div><b>現在這樣做</b><p role="status">{message}</p></div>{!['teach','mode','done'].includes(phase)&&<div><button onClick={help}>{mode==='challenge'?'我需要提示':'開啟提示'}</button><button onClick={()=>{setReview(!review);setLesson(0);}}>重看教學</button></div>}</section>
 {review&&teaching()}{phase==='teach'&&teaching()}
 {phase==='mode'&&<section className="sr-modes"><button onClick={()=>start('practice')}><span>01 / 一步一步做</span><h2>我要練習</h2><p>突出當前孔位、顯示下一步。可隨時重看教學。</p><b>開始練習 →</b></button><button onClick={()=>start('challenge')}><span>02 / 自己找出接點</span><h2>我要挑戰</h2><p>保留操作指示，自己判斷接法。求提示會轉練習，進度保留。</p><b>開始挑戰 →</b></button></section>}
 {['wire','observe','reconnect'].includes(phase)&&<><section className="sr-card"><div className="sr-section-head"><h2>{phase==='reconnect'?'只移除 A0，再自己接回。':'一顆 LDR，一顆固定電阻。'}</h2><span>無極性 · 每孔一個線頭</span></div><div className="sr-workbench"><div className="sr-parts"><div className="sr-next"><b>{power?'已通電：先拔 USB 才可改線':next?`下一步：${selected?'插入':'選取'}${selectedLabel}`:'端點齊備，檢查並測試'}</b>{!power&&next&&<p>{selected?'現在點':'選端點後，再點'}{hint?` ${target}（突出孔）`:'你判斷的目標孔'}。</p>}</div>{[['ldr1','ldr2','LDR 光敏電阻'],['r1','r2','一顆固定電阻']].map(([a,b,label])=><div className="sr-component" key={a}><strong>{label}</strong><svg viewBox="0 0 180 44" aria-hidden="true"><path d="M25 37L70 22M110 22L155 37" fill="none" stroke="#71847c" strokeWidth="3"/>{a==='ldr1'?<g><circle cx="90" cy="22" r="20" fill="#e8c794"/><path d="M78 11h24v6H78v6h24v6H78" stroke="#85552f" strokeWidth="3" fill="none"/></g>:<g><rect x="65" y="12" width="50" height="20" rx="5" fill="#dec096"/><path d="M77 12v20m9-20v20m9-20v20" stroke="#8b572a" strokeWidth="4"/></g>}</svg>{a==='r1'&&<label>電阻數值 <select aria-label="固定電阻數值" value={resistance} disabled={power} onChange={e=>{setResistance(Number(e.target.value));clearRun();}}><option value={10000}>10 kΩ（10000 Ω）</option><option value={220}>220 Ω</option></select></label>}{[a,b].map(p=><button key={p} disabled={power} aria-pressed={selected===p} onClick={()=>select(p as Part)}>{PARTS.find(([k])=>k===p)?.[1]}<small>{wiring[p as Part]||'未接'}</small></button>)}</div>)}<div className="sr-component"><strong>三條 Uno 接線</strong>{(['vcc','ground','input'] as Part[]).map(p=><button key={p} disabled={power} aria-pressed={selected===p} onClick={()=>select(p)}>{PARTS.find(([k])=>k===p)?.[1]}<small>{p==='vcc'?'5V':p==='ground'?'GND':'A0'} → {wiring[p]||'未接'}</small></button>)}</div>{hint&&<button onClick={()=>setHint(false)}>隱藏指定孔位</button>}</div><div><SensorBoard wiring={wiring} selected={selected} hint={hint} power={power} onSelect={select} onPlace={place} light={90-cover*.85}/><p className="sr-board-note">沿用工作紙方向：字母向右、數字向下。L = LDR、R = 電阻、A = A0。點已接端點可改接；線跨過孔不代表相通。窄畫面可左右捲動。</p><div className="sr-actions"><button onClick={togglePower}>{power?'拔除 USB':'連接 USB'}</button>{collecting&&<a href="#sensor-monitor">程式與 Serial Monitor ↓</a>}{phase==='wire'&&<button className="sr-primary" onClick={()=>{if(!circuit.ready){setMessage(circuit.text);return;}setPhase('observe');setSelected(null);setMessage('接線正確！接 USB，選 COM3，先驗證再上傳程式。之後開啟 Serial Monitor。');}}>檢查接線，前往讀數 →</button>}</div>{!circuit.safe&&<p className="sr-warning">{circuit.text}</p>}</div></div></section>
 {collecting&&<section ref={monitorSection} className="sr-card" id="sensor-monitor"><div className="sr-section-head"><h2>讓 Serial Monitor 收到數據。</h2><span>先驗證 → 上傳 → 開啟監控視窗</span></div><div className="sr-console-grid"><div className="sr-editor"><h3>Arduino 程式</h3><label>連接埠 <select aria-label="Uno 連接埠" value={port} onChange={e=>{setPort(e.target.value);setSamples([]);}}><option value="">選擇連接埠</option><option value="COM3">COM3 · Arduino Uno</option><option value="COM1">COM1 · 其他裝置</option></select></label><pre>void setup() {'{'}</pre><label><code>Serial.begin(</code><select aria-label="程式通訊速率" value={code.baud} onChange={e=>changeCode({...code,baud:Number(e.target.value)})}><option value={9600}>9600</option><option value={115200}>115200</option></select><code>);</code></label><pre>{'}'}{'\n'}void loop() {'{'}</pre><label><code>int sensorValue = analogRead(</code><select aria-label="analogRead 腳位" value={code.pin} onChange={e=>changeCode({...code,pin:e.target.value})}><option>A0</option><option>A1</option></select><code>);</code></label><label><input type="checkbox" checked={code.print} onChange={e=>changeCode({...code,print:e.target.checked})}/> <code>Serial.println(sensorValue);</code></label><label><code>delay(</code><select aria-label="取樣間隔毫秒" value={code.delay} onChange={e=>changeCode({...code,delay:Number(e.target.value)})}><option value={500}>500</option><option value={1000}>1000</option></select><code>);</code></label><pre>{'}'}</pre><div className="sr-actions"><button onClick={()=>{const error=validateCode(code);setVerified(!error);setMessage(error||'程式驗證通過：符合本課 A0、Serial.println、9600 及半秒取樣要求。現在上傳。');}}>驗證程式</button><button className="sr-primary" onClick={upload}>上傳程式</button></div><p>{verified?'✓ 本課程式檢核通過':'尚未通過本課程式檢核'} · {uploaded?'已有上傳版本':'尚未上傳'}</p><small>這是教學模擬，不是完整 IDE 編譯器。修改後需重新驗證及上傳。</small></div><div className="sr-monitor"><div className="sr-section-head"><h3>Serial Monitor</h3><button onClick={()=>{setMonitor(!monitor);setSamples([]);}}>{monitor?'關閉視窗':'開啟 Serial Monitor'}</button></div><label>監控視窗通訊速率 <select aria-label="監控視窗通訊速率" value={baud} onChange={e=>{setBaud(Number(e.target.value));setSamples([]);}}><option value={115200}>115200</option><option value={9600}>9600</option></select> baud</label><div className="sr-terminal" aria-label="序列讀數"><p>{serialError||'接收中 · 每半秒一行 · 原始值'}</p>{monitor&&!serialError&&<><div className="sr-latest">{samples.at(-1)?.value??'—'}<small>最新 analogRead(A0)</small></div><ol aria-label="最近讀數">{samples.slice(-6).map(s=><li key={s.number}>{s.value}</li>)}</ol></>}</div>{!circuit.ready&&<p className="sr-warning">{circuit.text}</p>}<details><summary>指令各做甚麼？</summary><p>analogRead(A0) 讀取輸入；sensorValue 儲存整數；Serial.println() 將它傳到電腦。電路斷開不是程式編譯錯誤。</p></details></div></div>
 <div className="sr-observe"><div><LightCover value={cover} onChange={changeCover} onMoving={setMovingCover}/><div className="sr-light-scene"><div><h3>用遮光改變輸入</h3><b>{environment.name}</b><small>LDR 光敏電阻</small></div><div className="sr-inline-reading"><b>{serialError?'—':samples.at(-1)?.value??'—'}</b><small>目前原始值</small></div></div><p>上下拉動遮光板，或選光度按鈕；放手後等三個新讀數，再記錄。相同條件也可能有小幅波動。</p><div className="sr-actions">{CONDITIONS.filter(c=>phase!=='reconnect'||c.id!=='shade').map(c=><button key={c.id} aria-pressed={condition===c.id} onClick={()=>{changeCover(c.id==='bright'?0:c.id==='shade'?50:100);}}>{c.name}</button>)}</div><p>目前：<strong>{environment.name}</strong> · 已收到 {serialError?0:Math.min(fresh.length,3)} / 3 個新讀數</p><button className="sr-primary" disabled={movingCover||!!serialError||!circuit.ready||fresh.length<3} onClick={record}>記錄這三個讀數</button></div>{recordsTable(table)}</div><p className="sr-note">模擬值只用來理解趨勢，並非實物測量或 lux。實物讀數會隨光源、LDR 型號和遮光程度改變。本課接法通常越光讀數越高。</p><div className="sr-actions">{phase==='observe'&&<button className="sr-primary" disabled={!CONDITIONS.every(c=>records[c.id].length===3)} onClick={()=>{setPhase('explain');setMessage('用剛才的讀數寫結論。選取光、暗各一個數值，說明規律與波動原因。');}}>三種光度已記錄，解釋結果 →</button>}{phase==='reconnect'&&<button className="sr-primary" disabled={retest.bright.length!==3||retest.dark.length!==3||!circuit.ready||!!serialError} onClick={()=>{setPhase('done');setMessage('完成！你已自己接回 A0，並以光暗讀數驗證電路。');}}>光暗重測成功，完成實驗 →</button>}</div></section>}</>}
 {phase==='explain'&&<section className="sr-card"><h2>讓你的讀數支持結論。</h2>{recordsTable(records)}<div className="sr-evidence"><label>光線充足時，我引用 <select aria-label="引用光線充足讀數" value={bright} onChange={e=>setBright(e.target.value)}><option value="">選擇表內讀數</option>{[...new Set(records.bright)].map(v=><option key={v}>{v}</option>)}</select></label><label>完全遮蓋時，我引用 <select aria-label="引用完全遮蓋讀數" value={dark} onChange={e=>setDark(e.target.value)}><option value="">選擇表內讀數</option>{[...new Set(records.dark)].map(v=><option key={v}>{v}</option>)}</select></label><label>比較後，本課接法越光 <select aria-label="光暗規律" value={trend} onChange={e=>setTrend(e.target.value)}><option value="">選擇規律</option><option value="higher">讀數越高</option><option value="lower">讀數越低</option><option value="same">讀數不變</option></select></label><label>這些數字表示 <select aria-label="讀數意義" value={unit} onChange={e=>setUnit(e.target.value)}><option value="">選擇</option><option value="raw">0–1023 的原始輸入值</option><option value="lux">照度 lux</option></select></label><label>同一情況有小幅波動，可能因為 <select aria-label="波動原因" value={factor} onChange={e=>setFactor(e.target.value)}><option value="">選一個合理因素</option><option value="shadow">手部遮光程度略有不同</option><option value="position">光源位置或環境光改變</option><option value="noise">感應器及取樣的微小波動</option><option value="broken">任何不同讀數都代表電路壞了</option></select></label></div><p className="sr-conclusion">我的證據：光 {bright||'___'}，暗 {dark||'___'}。{trend==='higher'?'越光讀數越高。':trend==='lower'?'越光讀數越低。':trend==='same'?'讀數不變。':'請完成規律。'}</p><button className="sr-primary" onClick={finishEvidence}>核對證據，開始獨立重接 →</button></section>}
 {phase==='done'&&<section className="sr-card sr-finish"><p className="sr-eyebrow">UNIT 03 COMPLETE</p><h2>{mode==='challenge'?'獨立完成！':'練習完成！'}</h2><p>你完成 LDR 分壓接線、Serial Monitor 讀數、三種光度記錄及 A0 獨立重接。</p>{recordsTable(records)}<p className="sr-conclusion">光線充足 {bright} ＞ 完全遮蓋 {dark}。本課接法越光，原始讀數越高。</p><p>使用提示 {hints} 次。下一單元可用這些輸入數據作判斷。</p><div className="sr-actions"><button className="sr-primary" onClick={download}>下載我的實驗記錄</button><a href={`${BASE}/`}>返回遊戲庫 →</a><button onClick={()=>location.reload()}>重新開始</button></div></section>}
 <footer>單元三 · 無聲音 · 不收集學生資料 · 重新整理會清除本次進度 <a href={`${BASE}/games/three-light-lab`}>複習單元二 ↗</a></footer></main>;
}
